### ISSUE TITLE
Could you please share the C code?

### ISSUE THREAD

**Issue by WEDM** [zecruel/cnc_8051#1]
Dear,

It is hard for me to read asm, could you please share the C code for 8051 MCU ?
Thanks a lot.
Regards,

Tau

**Comment by zecruel** [comment]
Hi,

Sorry, I didn't develop the code in a high-level language, because I don't think it would be functional. The 8051 microcontroller has very limited resources, where only in Assembly would it be possible to manage them.

Best regards,

Ezequiel

**Comment by WEDM** [comment]
Hi, Thank you for your reply.😀😀

Ezequiel ***@***.***> 于2021年10月16日周六 上午4:39写道：
